Keep LibreSSL 3.4.0 up-to-date for OpenBSD -current
sfackler/rust-openssl pull request #1479
Opened 2021-05-28 18:01 UTC by gonzalo-

I hope this is enough:

```
test result: ok. 46 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 8.95s

   Doc-tests openssl-sys

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Cheers.-

2021-05-28 19:45 UTC, sfackler commented
Looks like you need to run cargo fmt.

2021-05-28 19:53 UTC, sfackler commented
It looks like LibreSSL 3.4.0 hasn't released yet, so this will need to wait until it does.

2021-05-28 23:42 UTC, gonzalo- commented
> It looks like LibreSSL 3.4.0 hasn't released yet, so this will need to wait until it does.

sure, no problem.

2021-09-17 19:00 UTC, vishwin commented
3.4.0 is now released.

All of the guards that were for 3.3.2 and later need to stay that way instead of being redefined for 3.4.0. Otherwise the 3.3 branch, which is the stable branch, will most likely break.

2021-09-17 19:03 UTC, vishwin requested changes

2021-09-17 19:03 UTC, vishwin commented on openssl-sys/build/cfgs.rs
> +        if libressl_version >= 0x3_03_03_00_0 {
This is not necessary unless an actual guard condition in some other area of code is needed.

2021-09-17 19:03 UTC, vishwin commented on openssl-sys/build/main.rs
> +            (3, 4, _) => ('3', '4', 'x'),
Do not add 3.4.x until the 3.4 branch is considered stable.

2021-09-17 19:03 UTC, vishwin commented on openssl-sys/src/ssl.rs
> +    } else if #[cfg(libressl340)] {
This guard needs to stay at 3.3.2.

2021-09-17 19:03 UTC, vishwin commented on openssl/src/ssl/mod.rs
> +        #[cfg(any(ossl102, ossl110, libressl340))]
This guard needs to stay at 3.3.2.

2021-09-17 19:03 UTC, vishwin commented on openssl/src/ssl/mod.rs
> +        #[cfg(any(ossl102, ossl110, libressl340))]
This guard needs to stay at 3.3.2.

2021-09-17 19:03 UTC, vishwin commented on openssl-sys/build/main.rs
> +through 3.4.x, but a different version of OpenSSL was found. The build is now aborting
Should be 3.4.0 for now, per above comment.

2021-09-21 10:28 UTC, hargoniX commented
I'm currently trying to get some program that depends on openssl to work on -current and it's failing at the moment since this PR isn't merged yet. Is there any chance you'll get to addressing the review in the next days? @gonzalo- otherwise I'd happily take over the PR and fix it for you.

2021-09-21 10:29 UTC, gonzalo- commented
@hargoniX please take over, i will be off a few days, sorry guys

2021-09-21 10:54 UTC, hargoniX commented
Continued in #1524

2021-09-24 16:05 UTC, closed without merging